# Generated by Django 4.0.4 on 2022-05-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_data',
            name='last_scan',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
