# Generated by Django 4.0.4 on 2022-05-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_alter_scan_data_last_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_data',
            name='last_scan',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
