# Generated by Django 4.0.4 on 2022-05-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_participant_scan_data_delete_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='qr_code',
        ),
    ]
