# Generated by Django 4.0.4 on 2022-05-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_participant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
