# Generated by Django 4.0.4 on 2022-05-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_alter_scan_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan_data',
            options={},
        ),
    ]
