# Generated by Django 4.0.4 on 2022-05-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_alter_scan_data_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
