# Generated by Django 4.0.4 on 2022-05-11 08:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_alter_participant_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_data',
            name='scnanned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='qr.participant'),
        ),
    ]
