# Generated by Django 4.0.4 on 2022-05-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_scan_data_scnanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
