# Generated by Django 4.0.4 on 2022-05-16 22:39

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0009_participant_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_data',
            name='scnanned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, related_name='partdata', to='qr.participant'),
        ),
    ]
