# Generated by Django 4.0.4 on 2022-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0010_alter_scan_data_scnanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan_data',
            name='number_scans',
        ),
        migrations.AddField(
            model_name='scan_data',
            name='cin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan_data',
            name='scnanned',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
