# Generated by Django 4.0.4 on 2022-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0011_remove_scan_data_number_scans_scan_data_cin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='uid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
