# Generated by Django 4.0.4 on 2022-05-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0012_participant_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan_data',
            name='uid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
